{% set name = "vprtempo" %}
{% set version = "1.1.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9330228decb7d52eeeaf9ac32c23d481dcbf13b95667da84b5bb46bdf5f08067

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pytorch
    - torchvision
    - numpy
    - pandas
    - tqdm
    - prettytable
    - matplotlib-base
    - requests

test:
  imports:
    - vprtempo
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/QVPR/VPRTempo
  summary: 'VPRTempo: A Fast Temporally Encoded Spiking Neural Network for Visual Place Recognition'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamDHines
