{% set name = "vprtempo" %}
{% set version = "1.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c819254caeb7539c9a410cb2794ccecd76a71dbca6d2304cdf706138495306a2

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pytorch
    - torchvision
    - numpy
    - pandas
    - tqdm
    - prettytable
    - matplotlib-base

test:
  imports:
    - vprtempo
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/QVPR/VPRTempo
  summary: 'VPRTempo: A Fast Temporally Encoded Spiking Neural Network for Visual Place Recognition'
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AdamDHines
